<?php

class Paris2024Quiz extends Model {

	static $primaryKey = 'email';
	static $tableName = 'sns_paris2024_quiz';
	static $serialize = [];

	static public $tableKeys = [
		'email'   => '',
		'a_date' => '',
		'a_1' => '',
		'a_2' => '',
		'a_3' => '',
		'a_4' => '',
		'a_5' => '',
		'a_6' => '',
		'a_7' => '',
		'a_8' => '',
		'points' => 0
	];

    static function query($as = false): DBQuery
    {
        return parent::query($as)->select([
            'email',
            'a_date',
            'a_1',
            'a_2',
            'a_3',
            'a_4',
            'a_5',
            'a_6',
            'a_7',
            'a_8',
            'points'     
        ]); // TODO: Change the autogenerated stub
    }
}