<?php

class Paris2024Medals extends Model {

	static $primaryKey = 'country_id';
	static $tableName = 'sns_paris2024_medals';
	static $serialize = [];

	static public $tableKeys = [
		'country_id'   => 0,
		'country_name' => '',
		'gold'         => 0,
		'silver'       => 0,
		'bronze'       => 0,
		'amount'       => 0
	];

    static function query($as = false): DBQuery
    {
        return parent::query($as)->select([
            'country_id',
            'country_name',
            'gold',
            'silver',
            'bronze',
            'amount'
        ]); // TODO: Change the autogenerated stub
    }
}