<?php

class Paris2024Sport extends Model {

	static $primaryKey = 'sport_id';
	static $tableName = 'sns_paris2024_sports';
	static $serialize = [];

	static public $tableKeys = [
		'sport_id'   => 0,
		'sport_name' => '',
		'medals'     => 0
	];

    static function query($as = false): DBQuery
    {
        return parent::query($as)->select([
            'sport_id',
            'sport_name',
            'medals'
        ]); // TODO: Change the autogenerated stub
    }

}