<?php

class Paris2024Event extends Model {

	static $primaryKey = 'event_id';
	static $tableName = 'sns_paris2024_events';
	static $serialize = [
		'custom'
	];

	static public $tableKeys = [
		'event_id'   => 0,
		'sport_id'   => 0,
		'event_name' => '',
		'event_type' => '',
		'custom'     => '',
		'event_time' => 0
	];

	static $types = [
		'open'    => 'Церемония открытия',
		'close'   => 'Церемония закрытия',
		'compete' => 'Предварительные соревнования',
		'third'   => 'Матч за 3-е место',
		'final'   => 'Главные финалы',
	];

    static function query($as = false): DBQuery
    {
        return parent::query($as)->select([
            'event_id',
            'sport_id',
            'event_name',
            'event_type',
            'custom',
            'event_time'
        ]); // TODO: Change the autogenerated stub
    }

}