<?php

class Paris2024Table extends Model {

	static $primaryKey = 'tid';
	static $tableName = 'sns_paris2024_tables';
	static $serialize = [
		'table_header',
		'table_content'
	];

	static public $tableKeys = [
		'tid'           => 0,
		'sport_id'      => 0,
		'type'          => '',
		'table_name'    => '',
		'table_header'  => '',
		'table_content' => '',
		'updated_at'    => ''
	];

	static function filterDefaults( $args ) {
		$args['updated_at'] = current_time( 'mysql' );

		return $args;
	}

	static function query($as = false): DBQuery
    {
        return parent::query($as)->select([
            'tid',
            'sport_id',
            'type',
            'table_name',
            'table_header',
            'table_content',
            'updated_at'
        ]); // TODO: Change the autogenerated stub
    }

}